-- CRIAÇÃO DO BANCO DE DADOS.
CREATE DATABASE DB_SCF;

-- USANDO O BANCO DE DADOS.
USE DB_SCF;

-- CRIAÇÃO DAS TABELAS.
CREATE TABLE DB_SCF.TblTipoPagamento
(
TIPO_PAGAMENTO TINYINT NOT NULL,
DESCRICAO VARCHAR(20) NOT NULL,
PRIMARY KEY (TIPO_PAGAMENTO)
)
ENGINE = INNODB DEFAULT CHARSET = UTF8;

CREATE TABLE DB_SCF.TblContasPagas 
(
ID_CONTA_PAGAR INT NOT NULL AUTO_INCREMENT,
DESCRICAO VARCHAR(70) NOT NULL,
VALOR DECIMAL(8,2) NOT NULL,
PERIODO DATE NOT NULL,
TIPO_PAGAMENTO TINYINT NOT NULL,
PRIMARY KEY (ID_CONTA_PAGAR),

CONSTRAINT FK_CONTAS_PAGAR_TIPO_PAGAMENTO
FOREIGN KEY (TIPO_PAGAMENTO) 
REFERENCES TblTipoPagamento (TIPO_PAGAMENTO)
ON DELETE NO ACTION 
ON UPDATE NO ACTION
)
ENGINE = INNODB DEFAULT CHARSET = UTF8;

CREATE TABLE DB_SCF.TblContasReceber
(
ID_CONTA_RECEBER INT NOT NULL AUTO_INCREMENT, 
DESCRICAO VARCHAR(70) NOT NULL,
VALOR DECIMAL(8,2) NOT NULL,
PERIODO DATE NOT NULL,
TIPO_PAGAMENTO TINYINT NOT NULL,
PRIMARY KEY (ID_CONTA_RECEBER),

CONSTRAINT FK_CONTAS_RECEBER_TIPO_PAGAMENTO
FOREIGN KEY (TIPO_PAGAMENTO) 
REFERENCES TblTipoPagamento (TIPO_PAGAMENTO)
ON DELETE NO ACTION 
ON UPDATE NO ACTION
)
ENGINE = INNODB DEFAULT CHARSET = UTF8;


-- INSERTS.
INSERT INTO DB_SCF.TblTipoPagamento VALUES (1, 'VALOR TOTAL');
INSERT INTO DB_SCF.TblTipoPagamento VALUES (2, 'VALOR PARCIAL');

INSERT INTO DB_SCF.TblContasPagas VALUES (NULL, "Netflix", 22.90, now(), 1);
INSERT INTO DB_SCF.TblContasPagas VALUES (NULL, "Spotify", 14.90, now(), 1);
INSERT INTO DB_SCF.TblContasPagas VALUES (NULL, "Luz", 99, now(), 2);
INSERT INTO DB_SCF.TblContasPagas VALUES (NULL, "Blusa", 49.90, now(), 2);
INSERT INTO DB_SCF.TblContasPagas VALUES (NULL, "Calça", 149.90, now(), 2);

INSERT INTO DB_SCF.TblContasReceber VALUES (NULL, "Amigo 1", 20.90, now(), 1);
INSERT INTO DB_SCF.TblContasReceber VALUES (NULL, "Amigo 2", 100.50, now(), 1);
INSERT INTO DB_SCF.TblContasReceber VALUES (NULL, "Amigo 3", 10, now(), 1);


-- SELECTS.
SELECT * FROM DB_SCF.TblTipoPagamento;
SELECT * FROM DB_SCF.TblContasPagas;
SELECT * FROM DB_SCF.TblContasReceber;

-- DROP DATABASE DB_SCF;

SELECT * 
FROM DB_SCF.TblContasPagas cp
WHERE cp.PERIODO
BETWEEN (STR_TO_DATE(2000-01-01, '%Y-%m-%d')) AND (STR_TO_DATE(2070-01-01, '%Y-%m-%d')) 

SELECT * FROM TblContasReceber WHERE PERIODO BETWEEN ('2000-01-01') AND ('2070-01-01');

 SELECT * FROM TblContasReceber